# 旧 Mac の履歴用一覧。新 Mac の最小構成は Brewfile.macos を使う。
tap "homebrew/bundle"
brew "coreutils"
brew "fd"
brew "fish"
brew "fzf"
brew "gh"
brew "git"
brew "julia"
brew "jesseduffield/lazygit/lazygit"
brew "neovim"
brew "tree-sitter-cli"
brew "node"
brew "opam"
brew "ripgrep"
brew "rust"
brew "typst"
cask "anaconda"
